#ifndef __LFZL_CPPINTERFACE_CORE_FEATURE_READMEMORY_READMEMORY_H__
#define __LFZL_CPPINTERFACE_CORE_FEATURE_READMEMORY_READMEMORY_H__


#include <GameStruct.h>

BOOL InitializeReadMemory();

#endif // !__LFZL_CPPINTERFACE_CORE_FEATURE_READMEMORY_READMEMORY_H__
